# Generated by Django 2.0.7 on 2019-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
