# Generated by Django 2.2 on 2019-04-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190420_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherInfo',
        ),
    ]
