# Generated by Django 2.1.2 on 2019-05-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_teacherinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_short_form', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_section', models.CharField(max_length=50)),
                ('std_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentClassInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentShiftInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='address',
            field=models.CharField(default='kushtia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='fathers_name',
            field=models.CharField(default='mr. a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='roll',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailinfo',
            name='std_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentShiftInfo'),
        ),
        migrations.AddField(
            model_name='studentdetailinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
    ]
