# Generated by Django 2.1.2 on 2019-05-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190517_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailinfo',
            name='session',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
