# Generated by Django 2.1.2 on 2019-06-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190622_1546'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdetailinfo',
            unique_together={('roll', 'std_class')},
        ),
    ]
